config/routes.rb
Rails.application.routes.draw do


  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }



    scope module: :public do
      root to: 'homes#top'
    get 'my_page' => 'customers#show'
    get 'about' => 'homes#about'
    get 'information' => 'customers#edit'
    get 'unsubscribe' => 'customers#unsubscribe'
    get 'orders/thanx'
    patch 'withdraw' => 'customers#withdraw', as: 'withdraw'
    delete 'destroy_all' => 'cart_items#destroy_all'
    post 'orders/confirm'
    resources :homes, only: [:top, :about]
    resources :items, only: [:index, :show]
    resources :customers, only: [:show, :edit, :unsubscribe, :update, :withdraw]
    resources :cart_items, only: [:index, :update, :destroy, :destroy_all, :create]
    resources :orders, only: [:new, :thanx, :index, :show, :confirm, :create,]
  end

  namespace :admin do
    root to: 'homes#top'
   resources :orders, only: [:show, :update]
   resources :order_details, only: [:update]

   resources :customers, only: [:index, :show, :edit, :update]
   resources :items, only: [:new, :index, :create, :show, :edit, :update]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def address_display
    '〒'+postal_code+''+address+''+name
  end

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_deposit: 0, deposit_confirmation: 1, cooking: 2, shipping_preparing: 3, shipped: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "deposit_confirmation"
    end
    redirect_to admin_order_path(@order.id)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-md-2">注文履歴詳細</h4>
  </div>
  <table class="col-md-4">
    <tr>
      <td>購入者</td>
      <td><%= link_to @order.customer.first_name, admin_customer_path(@order.customer.id) %><%= link_to @order.customer.last_name, admin_customer_path(@order.customer.id) %></td>
    </tr>
    <tr>
      <td>注文日</td>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <td>配送先</td>
      <td><%= @order.address %></td>
    </tr>
    <tr>
      <td>支払方法</td>
      <td><%= @order.payment_method_i18n %></td>
    </tr>
    <tr>
      <td>注文ステータス</td>
      <td>
        <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
        <%= f.select :status, Order.statuses.keys.map { |k| [I18n.t("enums.order.status.#{k}"), k] } %>
        <%= f.submit "更新", class: "btn btn-success btn-sm" %>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="row my-3">
    <table class="table col-md-7 ">
      <thead class="thead-light">
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.item.price %></td>
          <td><%= order_detail.amount %></td>
          <td><%= order_detail.subtotal %></td>
          <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
            <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"), k] } %>
            <%= f.submit "更新", class: "btn btn-success btn-sm" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <table class="table table-sm col-md-2 table-borderless ">
      <tr>
        <% @product_total = 0 %>
        <% @order_details.each do |total| %>
        <% @product_total += total.subtotal %>
        <% end %>
        <td class="align-bottom">商品合計</td>
        <td class="align-bottom"><%= @product_total %>円</td>
      </tr>
      <tr>
        <td class="align-bottom">送料</td>
        <td class="align-bottom"><%= @order.shipping_cost %>円</td>
      </tr>
      <tr>
        <td class="align-bottom">請求金額合計</td>
        <% product_totals = @product_total + @order.shipping_cost %>
        <td class="align-bottom"><%= product_totals %>円</td>
      </tr>
    </table>
  </div>
</div>